### ISSUE TITLE
Output: umount: can't unmount Invalid argument

### ISSUE THREAD

**Issue by 2232729885** [yandex-cloud/geesefs#107]
restart container, but the csi-s3 occur errors
![image](https://github.com/yandex-cloud/geesefs/assets/138634190/2618f526-abf1-4e2e-ac94-a38b40afff6f)

**Comment by 2232729885** [comment]
but if i create a new container, it will be mount s3 successfully

**Comment by 2232729885** [comment]
It's worth noting that the CSI-S3 container has been restarted beause of host occured oom killer

**Comment by vitalif** [comment]
You're probably right, I also think it was caused by the OOM
I think it's fine if you're able to mount the pvc into a new container and then unmount it after this error
Please post csi-s3 issues to https://github.com/yandex-cloud/k8s-csi-s3/issues by the way :-)
