### ISSUE TITLE
Не монтируется повторно самотоятельно если geesefs убил OOM

### ISSUE THREAD

**Issue by SaymonDzen** [yandex-cloud/geesefs#12]
Пришел ООM во время бэкапа
```
Oct 20 18:03:22 storage-new kernel: [15748.775876] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/mnt-s3-support_files.mount,task=geesefs,pid=883,uid=0
Oct 20 18:03:22 storage-new kernel: [15748.775915] Out of memory: Killed process 883 (geesefs) total-vm:4499164kB, anon-rss:2332184kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:5776kB oom_score_adj:0
Oct 20 18:03:22 storage-new kernel: [15748.861969] oom_reaper: reaped process 883 (geesefs), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

proxmox-backup client
```
catalog upload error - channel closed
Error: error at "140201/test000.ts": Transport endpoint is not connected (os error 107)
```
mount -a
df -h /mnt/s3/support_files
df: /mnt/s3/support_files: Transport endpoint is not connected
umount -f /mnt/s3/support_files
mount -a
df -h /mnt/s3/support_files
Filesystem      Size  Used Avail Use% Mounted on
support-files   1.0P     0  1.0P   0% /mnt/s3/support_files
```

**Comment by vitalif** [comment]
К 0.30.3 тут изменено 2 вещи:
1) Учащена сборка мусора, дабы не съедать двойной относительно лимита объём памяти
2) Сделано, чтобы GeeseFS не умирал при внутреннем OOM (когда не может выделить буфер под данные, не превысив --memory-limit), а только возвращал ошибку ENOMEM
Помимо этого пока тут ничего делать не планируется, так что прикрою
