### ISSUE TITLE
Unstable when copy many files

### ISSUE THREAD

**Issue by AlexZIX** [yandex-cloud/geesefs#17]
We use our tool written in C# which every night copy many files (approx. 3000 files with 30 GB total size) from local storage to S3 bucket mounted as disk using geesefs. Process started at 3:00 at night and after 30 minutes shows the following error:

Dec 28 07:31:39 wp-angstrem /sbin/geesefs[159621]: fuse.ERROR *fuseops.LookUpInodeOp error: permission denied
Dec 28 03:30:50 wp-angstrem wigwam-api[21726]: #033[41m#033[30mfail#033[39m#033[22m#033[49m: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
Dec 28 03:30:50 wp-angstrem wigwam-api[21726]:       An unhandled exception has occurred while executing the request.
Dec 28 03:30:50 wp-angstrem wigwam-api[21726]: System.UnauthorizedAccessException: Access to the path '/archive-s3/webplanner/12/36/1236584.b3db' is denied.
Dec 28 03:30:50 wp-angstrem wigwam-api[21726]:  ---> System.IO.IOException: Permission denied
Dec 28 03:30:50 wp-angstrem wigwam-api[21726]:    --- End of inner exception stack trace ---

When our tool copy files from one local disk to another all works fine. Seems that it's an issue of geesefs. Can you please explain what does this error means?

**Comment by vitalif** [comment]
Hi, I can't easily tell what caused that "permission denied" error in your case.
Are there any other errors in the log? For example, anything related to HTTP requests returning 403?
