### ISSUE TITLE
Problem with reading many files

### ISSUE THREAD

**Issue by entasadar** [yandex-cloud/geesefs#18]
I try to execute `ls` (1500 small files in a directory `bucket_name/directory`), but it freeze. 
After ~20 min I got message:
`ls: reading directory '.': Software caused connection abort` and lost connection :(

I can execute `ls` on the same directory with goofys.

**Comment by vitalif** [comment]
Hi, please capture the debug log as stated in README in Troubleshooting section and attach it here

**Comment by vitalif** [comment]
And one suggestion - maybe you have to start geesefs with `--list-type 2` if you don't use Yandex S3.

**Comment by entasadar** [comment]
Hi! Thanks, your suggestion is right.
I use minio and `--list-type 2` works for me:)
