### ISSUE TITLE
Binary only installation does not allow to work with fstab

### ISSUE THREAD

**Issue by FractalizeR** [yandex-cloud/geesefs#19]
When you use geesefs just with downloading binary, just adding an entry to fstab produces the following error:
```$ sudo nano /etc/fstab
$ sudo mount -a
/bin/sh: 1: geesefs: not found```

What should you do to provide fuse with a knowledge, that the handler for `fuse.geesefs` filesystem type resides in a binary, that you've just downloaded (this should be added into installation documentation I think)?

**Comment by vitalif** [comment]
Hi, put it into PATH, for example into /usr/bin or /usr/local/bin and make it executable, that's all

**Comment by FractalizeR** [comment]
That is - you need to copy downloaded binary into `/bin/geesefs`

**Comment by FractalizeR** [comment]
Yeah, thanks, just figured that out
