### ISSUE TITLE
 s3.ERROR code=NoCredentialProviders msg=no valid providers in chain.

### ISSUE THREAD

**Issue by izedgo** [yandex-cloud/geesefs#2]
Почему-то не подхватывает файл $HOME/.aws/credentials и выдает ошибку.
При передаче AWS_ACCESS_KEY_ID и AWS_SECRET_ACCESS_KEY через env все работает нормально.

**Comment by vitalif** [comment]
Привет, да, баг был внесён вчера вместе с опцией --shared-config, сегодня в 0.28.4 уже исправлен. :-)
