### ISSUE TITLE
Running inside docker without privileges?

### ISSUE THREAD

**Issue by doochik** [yandex-cloud/geesefs#20]
I am trying to run geesefs inside docker.

All works fine when I add privileges to container
`docker run --rm -it --device /dev/fuse --cap-add SYS_ADMIN <image> /bin/bash`

But it doesn't work without `--cap-add`

```sh
$ docker run --rm -it -v /lib/modules:/lib/modules <image> /bin/bash

root@6b40303f1416:$ modprobe fuse
root@6b40303f1416:$ AWS_ACCESS_KEY_ID=<key> AWS_SECRET_ACCESS_KEY=<secret> geesefs -f --endpoint <endpoint> <bucket>:<path> /tmp/geesefs-mountpoint
/usr/bin/fusermount: fuse device not found, try 'modprobe fuse' first
2022/02/04 10:28:24.830729 main.FATAL Mounting file system: Mount: mount: running /usr/bin/fusermount: exit status 1
```

Any way to make it work?

Dockerfile
```
FROM ubuntu:focal

RUN apt-get update -qq && apt-get install -y fuse kmod && rm -rf /var/lib/apt/lists/*

COPY ./geesefs-linux-amd64 /usr/bin/geesefs

RUN mkdir /tmp/geesefs-mountpoint
```

**Comment by vitalif** [comment]
Hi, I suspect there's no way to use FUSE in Docker without SYS_ADMIN or privileged containers. I've never seen any instructions to do that. If you find a way, make me know, I'm also curious :)
