### ISSUE TITLE
Enormous memory usage

### ISSUE THREAD

**Issue by shadowlmd** [yandex-cloud/geesefs#23]
I have a bucket with over 6 million objects mounted using geesefs like this:
```
/opt/geesefs/bin/geesefs --dir-mode 0750 --file-mode 0640 --cache-file-mode 0640 -f my-bucket /mnt/my-bucket
```
After running rsync for almost two days to syncrhonize data that mostly already exists in the bucket, I noticed very high memory usage:
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
3390745 www-data  20   0   10.5g   7.8g   7312 R 146.5  33.5   1502:09 geesefs
```
And it keeps growing.

**Comment by shadowlmd** [comment]
I'm afraid I won't be able to do any more testing because after facing these two serious issues we decided not to use YC Object Storage and the bucket is already deleted.

**Comment by vitalif** [comment]
Sad to hear that :-) anyway, we can try to debug your issue if you decide to use it again. For now I'm closing this issue
