### ISSUE TITLE
Trust evaluate failures

### ISSUE THREAD

**Issue by ejm714** [yandex-cloud/geesefs#24]
I'm attempting to use geesefs on an M1 Mac. I've downloaded the appropriate binary, made it executable, moved it to `/usr/local/bin`, and installed macfuse. 

When I run geesefs `geesefs {bucket_name} {mount_point`, I get `main.FATAL Unable to mount file system, see syslog for details`.

In the console, I see a number of `Trust evaluate failure: [leaf TemporalValidity]` entries. How can I resolve these so I can use geesefs?

<img width="931" alt="image" src="https://user-images.githubusercontent.com/22667367/156277457-78ec01b2-d031-498d-8433-62b13df69c9a.png">

**Comment by vitalif** [comment]
Hi, no idea what it is. I don't use macos, but my colleagues who do also don't know what it is :-)
But I suppose it's not syslog, and these errors aren't what you're looking for. Try to start geesefs with `-f` and it will stay in the foreground and you should see the actual error message :-)

**Comment by ejm714** [comment]
Very helpful, you're right that trust failure was a red herring. Running `geesfs -f <bucket> <mount>` yields a helpful error, which is that the bucket does not exist.

Can you help me specify the proper configuration for an s3 bucket? It seems like I need to specify an endpoint value per the help, but using the s3 example from the help text produces this error about colons.


```
❯ geesefs --endpoint value="https://s3.amazonaws.com" test_bucket my_mount
2022/03/02 12:35:25.234901 s3.ERROR Unable to access 'test_bucket': parse "value=https://s3.amazonaws.com": first path segment in URL cannot contain colon
2022/03/02 12:35:25.235231 s3.ERROR code=InvalidEndpointURL msg=invalid endpoint uri, err=parse "value=https://s3.amazonaws.com/{Bucket}/{Key+}": first path segment in URL cannot contain colon
```

**Comment by vitalif** [comment]
What made you think you need value= in front of the endpoint? Just pass it as `--endpoint https://...` and it will work :-)

**Comment by vitalif** [comment]
I.e did you take it from docs/help from somewhere?

**Comment by ejm714** [comment]
Nope just a silly mistake, I had read the flag as "endpoint value" rather than just "endpoint." All works now, thank for the assist!
