### ISSUE TITLE
fuse.ERROR writeMessage: invalid argument [80 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]

### ISSUE THREAD

**Issue by alex-v-jc** [yandex-cloud/geesefs#3]
Добрый день.

При попытке подключиться к Yandex Object Storage получаю такую ошибку:

```
-----------------------------------------------------
2021/09/30 16:19:52.769225 fuse.DEBUG Op 0x00000001        connection.go:411] <- init
2021/09/30 16:19:52.769257 fuse.DEBUG Op 0x00000001        connection.go:500] -> OK ()
2021/09/30 16:19:52.769278 fuse.ERROR writeMessage: invalid argument [80 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
2021/09/30 16:19:52.769294 main.INFO File system has been successfully mounted.
2021/09/30 16:19:52.785066 s3.DEBUG DEBUG: Response s3/ListMultipartUploads Details:
---[ RESPONSE ]--------------------------------------
```

В итоге папка подключается, но:

```
ls -lha
ls: cannot access share: Connection refused

d??????????  ? ?    ?       ?            ? share
```

Что с дефолтными параметрами запуска:

```
./geesefs -f --debug_s3 --debug_fuse --debug share /mnt/share
```
что при изменения каких-либо параметров, в частности, `--dir-mode` и `--file-mode`, результат и ошибка не меняются.

При этом, запуск

```
./goofys -f --debug_s3 --debug_fuse share /mnt/share
```

приводит к корректному подключению:
```
-----------------------------------------------------
2021/09/30 16:34:03.086817 fuse.DEBUG Op 0x00000001        connection.go:408] <- init
2021/09/30 16:34:03.086842 fuse.DEBUG Op 0x00000001        connection.go:491] -> OK ()
2021/09/30 16:34:03.086871 main.INFO File system has been successfully mounted.
2021/09/30 16:34:03.098758 s3.DEBUG DEBUG: Response s3/ListMultipartUploads Details:
---[ RESPONSE ]--------------------------------------
```
```
drwxr-xr-x.  2 root root 4.0K Sep 30 16:34 share
```

Не могли бы указать причину и способ устранения?
Спасибо!

**Comment by vitalif** [comment]
Здравствуйте, что-то здесь не так, я постоянно тестирую на яндексовом s3, вроде такого не наблюдаю... Учитывая, что есть какое-то сообщение о fuse, подскажите версию ядра?

**Comment by vitalif** [comment]
Не понятно, проверил даже на centos 7, всё равно работает почему-то :-)

**Comment by alex-v-jc** [comment]
> Не понятно, проверил даже на centos 7, всё равно работает почему-то :-)

Вот тут подробнее )
Я где-то пропустил, что на CentOS 7 не должно работать?
У меня как раз CentOS 7

```
Linux vmlinuz-3.10.0-957.5.1.el7.x86_64
(gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Fri Feb 1 14:54:57 UTC 2019

centos-release-7-6.1810.2.el7.centos.x86_64
```

> Учитывая, что есть какое-то сообщение о fuse, подскажите версию ядра?

```
fuse-2.9.2-11.el7.x86_64

geesefs 0.28.4
```

С s3fs V1.90 проблем нет.
С goofys 0.24.0-45b8d78375af1b24604439d2e60c567654bcdf88 тоже.

**Comment by alex-v-jc** [comment]
> я постоянно тестирую на яндексовом s3 (и в яндексовых вм)

Да, я тоже работаю с Yandex Cloud и с подключаюсь с их VM.

> Не понятно, проверил даже на centos 7, всё равно работает почему-то :-)

У меня есть VM с CentOS 8, проверил на ней, проблем не возникло.
Все же, есть зависимости от ОС?

Если это так, это немного печально, так как две VM, которые нуждаются в подключении хранилища, причем именно через GeeseFS из-за работы с большим количеством маленьких файлов, используют CentOS 7.
Не хотелось бы поднимать вопрос об обновлении ОС.

**Comment by vitalif** [comment]
Проверю сейчас ещё с fuse 2. Я сейчас проверял на centos 7 с fuse 3. Может есть какой-то баг именно с fuse 2, какая-нибудь фича новая неподдерживаемая

**Comment by vitalif** [comment]
Можете кстати попробовать просто установить yum install fuse3, видимо заработает

**Comment by alex-v-jc** [comment]
Ок, попробую, надо будет тогда удалить fuse2, наверное, отпишусь по результату...
Но, с `fuse-2.9.7-12.el8.x86_64` на CentOS 8 проблем не возникает.

**Comment by alex-v-jc** [comment]
Просто `yum install fuse3` результата не поменял.
При этом, избавиться от `fuse-libs-2.9.2-11.el7.x86_64` не получается (есть зависимости).

Сейчас в системе:

```
# rpm -qa | grep fuse

fuse3-libs-3.6.1-4.el7.x86_64
fuse3-3.6.1-4.el7.x86_64
fuse-libs-2.9.2-11.el7.x86_64
fuse-2.9.2-11.el7.x86_64
```

Какую версию и библиотеку будет использовать GeeseFS?
Надо что-то где-то указывать?

Я повторил установку на VM в другом ДЦ, с такой же системой.
В итоге, имеем

```
centos-release-7-6.1810.2.el7.centos.x86_64
vmlinuz-3.10.0-957.el7.x86_64
```

Установку fuse3:

```
# yum install fuse3

...
Running transaction
  Installing : fuse3-libs-3.6.1-4.el7.x86_64                                                                                                                                                                                                                          1/2
  Installing : fuse3-3.6.1-4.el7.x86_64                                                                                                                                                                                                                               2/2
  Verifying  : fuse3-libs-3.6.1-4.el7.x86_64                                                                                                                                                                                                                          1/2
  Verifying  : fuse3-3.6.1-4.el7.x86_64                                                                                                                                                                                                                               2/2

Installed:
  fuse3.x86_64 0:3.6.1-4.el7

Dependency Installed:
  fuse3-libs.x86_64 0:3.6.1-4.el7
```

```
# rpm -qa | grep fuse

fuse3-libs-3.6.1-4.el7.x86_64
fuse3-3.6.1-4.el7.x86_64
fuse-libs-2.9.2-11.el7.x86_64
fuse-2.9.2-11.el7.x86_64
```

Запуск:

```
/usr/local/bin/geesefs -f --debug_s3 --debug_fuse --debug cgp.share /mnt/share/
```

Результат:

```2021/10/01 20:54:37.248889 fuse.DEBUG Ref 1 . [1]
2021/10/01 20:54:37.248907 fuse.DEBUG Ref 1 .. [1]
2021/10/01 20:54:37.249379 fuse.DEBUG Op 0x00000001        connection.go:411] <- init
2021/10/01 20:54:37.249413 fuse.DEBUG Op 0x00000001        connection.go:500] -> OK ()
2021/10/01 20:54:37.249494 fuse.ERROR writeMessage: invalid argument [80 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
```

Очень хочется решить проблему, особенно, принимая во внимание то, что у вас все работает на аналогичной системе.
Есть идеи куда копать?
Спасибо!

**Comment by vitalif** [comment]
Хм. Ну ещё такой вариант: я проверял на ядре 3.10.0-1160.11.1.el7.x86_64, оно немного поновее, попробуйте обновить...

**Comment by alex-v-jc** [comment]
Будем считать вопрос уже не актуальным.
Заставить работать на CentOS 7 я так и не смог.
Было принято решение обвиться до CentOS 8.
После обновления, все начиналось хорошо, но... увы, не долго.
Подробности в issue #5

**Comment by vitalif** [comment]
Ну тут вопрос в ядре, invalid argument [80 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0] - это значит, что ядро не понимает опцию, которую просит fuse. Я потом повыяснял, где это сломалось, я так понимаю, это FUSE_MAX_PAGES. Формально оно добавлено, вроде бы, аж в 4.19, но центосные ядра отличаются тем, что их после выпуска ещё 10 лет патчат индусы, бэкпортируя туда фичи, и поэтому ничего удивительного в том, что в какой-то относительно свежей сборке их 3.10 есть эта фича, в общем-то, нет. А Goofys собран с более старой версией биндинга @jacobsa/fuse, поэтому и работает.

**Comment by dezeptip** [comment]
ls: cannot access share: Connection refused

d??????????  ? ?    ?       ?            ? share

была та же проблема, нашли параметр подключения allow_other и заработало для остальных пользователей
