### ISSUE TITLE
macos cannot copy to mounted directory

### ISSUE THREAD

**Issue by abrekhov** [yandex-cloud/geesefs#30]
Hi everyone! 

macOS 10.15.7 (19H1615)

I've installed prebuilt binary for mac/amd64. 

In one window doing this

```
sudo geesefs -f --endpoint https://storage.yandexcloud.net/ my-videos videos
2022/04/20 16:28:07.687106 main.INFO File system has been successfully mounted.
```

On the other window 

```
ls
ls: videos: No such file or directory
```

**Comment by vitalif** [comment]
Hi, no idea about macos, but I guess you need to mount it either with `-o allow_other` or without sudo

**Comment by abrekhov** [comment]
> Hi, no idea about macos, but I guess you need to mount it either with `-o allow_other` or without sudo

I've already run with sudo... I'll try with allow_other

**Comment by vitalif** [comment]
Thing is that when you mount it under root, only root has access to it

**Comment by abrekhov** [comment]
> Hi, no idea about macos, but I guess you need to mount it either with `-o allow_other` or without sudo

Everything is good if mounting without sudo but wit -o allow_other

My solution is 

```
# first tab
geesefs -f --endpoint https://storage.yandexcloud.net/ -o allow_others my-videos videos
2022/04/20 16:52:35.771887 main.INFO File system has been successfully mounted.
```

```
# second tab
rsync -ah --progress ~/Desktop/my-videos/*mp4 videos
building file list ...
4 files to consider
06ac69ee-7cf9-4a79-af48-5f095b2e9dee.mp4
       1.84G  17%    6.30MB/s    0:22:40
```

**Comment by vitalif** [comment]
Is -o allow_other**s** a typo?
