### ISSUE TITLE
Docker bind mount "permission denied"

### ISSUE THREAD

**Issue by almson** [yandex-cloud/geesefs#33]
How can I launch a docker container that maps a mounted directory on the host?

`docker -v /home/user/src:/target ...` 

gives

```docker: Error response from daemon: error while creating mount source path '/home/user/src': mkdir /home/user/src: file exists.```

while

`--mount type=bind,source=/home/user/src,destination=/data`

gives

`docker: Error response from daemon: invalid mount config for type "bind": stat /home/user/src: permission denied.`

**Comment by yashumitsu** [comment]
Hi, it's common behaviour fo FUSE filesystem.

1. uncomment user_allow_other in /etc/fuse.conf
2. mount geesefs with ```-o allow_other```

should help

**Comment by eriksjolund** [comment]
I noticed that `-o allow_other` is not needed when using 


```
$ podman run --rm --user 0:0 \
    --security-opt label=disable \
    -v /mnt/geesefs:/dir \
        docker.io/library/fedora touch /dir/testfile
$
```

In the example above I could  also have removed `--user 0:0` as it is the  default when  `USER` has not been set inside the container image.

There is no `USER` in the container image __docker.io/library/fedora__
```
$ podman image inspect --format '{{.Config.User}}' docker.io/library/fedora

$
```


I didn't mount _/mnt/geesefs_ with xattr support
so I had to provide the argument `--security-opt label=disable`.
