### ISSUE TITLE
Wasabi S3 compatibility issue: s3/ListObjects status code 500

### ISSUE THREAD

**Issue by xangelix** [yandex-cloud/geesefs#43]
[Wasabi](https://wasabi.com/) is another cloud provider of S3 at very competitive speeds and prices. Unfortunately, there seems to be a compatibility issue with geesefs which is not present with goofys or s3fs, related to a part of the S3 spec they must be differing in somehow.

To reproduce:
```
geesefs --endpoint https://s3.wasabisys.com mybucket /mnt

mkdir /mnt/a
ls /mnt/a     [SUCCEEDS]
ls /mnt       [ALWAYS SUCCEEDS]

geesefs SIGINT
geesefs --endpoint https://s3.wasabisys.com mybucket /mnt

ls /mnt/a     [FAILS --> ls: reading directory '/mnt/a': Resource temporarily unavailable]
ls /mnt       [ALWAYS SUCCEEDS]
ls /mnt/a     [SUCCEEDS]
```
No matter how many directories deep, unless the directory above it was read first (or recently??), it fails with the status code 500 errors.
On that failure, these errors occur:

```
2022/08/03 19:15:16.014305 s3.DEBUG DEBUG: Validate Response s3/ListObjects failed, attempt 2/3, error InternalError: We encountered an internal error.  Please retry the operation again later.
        status code: 500, request id: <redacted>, host id: <redacted>
2022/08/03 19:15:16.210893 s3.DEBUG DEBUG: Request s3/ListObjects Details:
---[ REQUEST POST-SIGN ]-----------------------------
GET /demo8?marker=a.%F4%8F%BF%BF&prefix= HTTP/1.1
Host: s3.wasabisys.com
User-Agent: GeeseFS/0.31.5 (go1.16.15; linux; amd64)
Accept-Encoding: identity
Authorization: AWS4-HMAC-SHA256 Credential=<redacted>/20220803/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-date, Signature=<redacted>
X-Amz-Content-Sha256: <redacted>
X-Amz-Date: <redacted>


-----------------------------------------------------
2022/08/03 19:15:16.326267 s3.DEBUG DEBUG: Response s3/ListObjects Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 500 Internal Server Error
Connection: close
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Wed, 03 Aug 2022 23:15:16 GMT
Server: WasabiS3/7.5.1035-2022-06-08-c4b39686a7 (head07)
X-Amz-Bucket-Region: us-east-1
X-Amz-Id-2: <redacted>
X-Amz-Request-Id: <redacted>
```

I have also reached out to Wasabi support to inquire about this issue, but given your understanding of geesefs's internals, if you could provide a solution to above, or some sort of compatibility mode, it would be very greatly appreciated. Wasabi does offer a free trial which may aid debugging, and I would be more than happy to do anything possible on my side to help.

**Comment by vitalif** [comment]
Hi, 500 is definitely their bug, but you can try --list-type 2 or --list-type 1. GeeseFS by default tries yandex-specific list-type=ext-v1, then falls back to list-type=1 if it gets InvalidArgument, NotImplemented, or a non-matching response. But yeah, it doesn't fall back to list-type=1 on 500 :)

**Comment by xangelix** [comment]
Tried list-type 1 and 2 and unfortunately didn't see any improvement. Is there any information about the problem I'm having and how geesefs works that would be good to pass on to the Wasabi Support people? Or should they have a good idea?

**Comment by vitalif** [comment]
Okaaay... Another idea is that it could be caused by %F4%8F%BF%BF in marker - this is how geesefs emulates 'greater than' operator for listings. It corresponds to 0x10FFFF - largest possible code point in UTF-8. It's required to list keys that are greater than some prefix + '/'. Maybe this character crashes their service?

**Comment by xangelix** [comment]
While this page mentions only filenames, perhaps it could be related to this, then?
https://wasabi-support.zendesk.com/hc/en-us/articles/360002101712-Does-Wasabi-support-4-byte-UTF8-characters-

**Comment by vitalif** [comment]
In fact I rechecked and I think this ">=" emulation is not needed anymore. So I just committed a fix. Please try to build the version from master branch

**Comment by xangelix** [comment]
that seems to have done it, thank you so much!
