### ISSUE TITLE
Падает вот с такой ошибкой

### ISSUE THREAD

**Issue by alglyzin** [yandex-cloud/geesefs#47]
fatal error: sync: unlock of unlocked mutex

goroutine 12 [running]:
runtime.throw({0xfe66ae, 0xc025d56f60})
	/usr/lib/golang/src/runtime/panic.go:1198 +0x71 fp=0xc00004bed8 sp=0xc00004bea8 pc=0x43b931
sync.throw({0xfe66ae, 0x1})
	/usr/lib/golang/src/runtime/panic.go:1184 +0x1e fp=0xc00004bef8 sp=0xc00004bed8 pc=0x469d5e
sync.(*Mutex).unlockSlow(0xc00035a7b8, 0xffffffff)
	/usr/lib/golang/src/sync/mutex.go:196 +0x3c fp=0xc00004bf20 sp=0xc00004bef8 pc=0x478cdc
sync.(*Mutex).Unlock(0x0)
	/usr/lib/golang/src/sync/mutex.go:190 +0x29 fp=0xc00004bf40 sp=0xc00004bf20 pc=0x478c69
sync.(*Cond).Wait(0xc025d56f60)
	/usr/lib/golang/src/sync/cond.go:55 +0x7e fp=0xc00004bf78 sp=0xc00004bf40 pc=0x476e9e
github.com/yandex-cloud/geesefs/internal.(*Goofys).FDCloser(0xc00035a6c0)
	/root/geesefs/internal/goofys.go:344 +0x67 fp=0xc00004bfc8 sp=0xc00004bf78 pc=0xd2c647
github.com/yandex-cloud/geesefs/internal.newGoofys·dwrap·33()
	/root/geesefs/internal/goofys.go:268 +0x26 fp=0xc00004bfe0 sp=0xc00004bfc8 pc=0xd2c1c6
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00004bfe8 sp=0xc00004bfe0 pc=0x46eee1
created by github.com/yandex-cloud/geesefs/internal.newGoofys
	/root/geesefs/internal/goofys.go:268 +0xaf1

goroutine 1 [select, 2215 minutes]:
github.com/jacobsa/fuse.(*MountedFileSystem).Join(0xc0003eaea0, {0x11cd1a8, 0xc0000a8000})
	/root/go/pkg/mod/github.com/vitalif/fusego@v0.0.0-20220702223751-e304003d79bf/mounted_file_system.go:43 +0x7b
main.main.func2(0xc0000ef4a0)
	/root/geesefs/main.go:242 +0x63e
github.com/urfave/cli.HandleAction({0xe35900, 0xc0000c7b40}, 0xd)
	/root/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190807111034-521735b7608a/app.go:514 +0xa8
github.com/urfave/cli.(*App).Run(0xc000396380, {0xc0003b2300, 0xd, 0x10})
	/root/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190807111034-521735b7608a/app.go:274 +0x754
main.main()
	/root/geesefs/main.go:254 +0x165

goroutine 21 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000116600)
	/root/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xb9
created by go.opencensus.io/stats/view.init.0
	/root/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x92

goroutine 3 [syscall, 2215 minutes]:
os/signal.signal_recv()
	/usr/lib/golang/src/runtime/sigqueue.go:169 +0x98
os/signal.loop()
	/usr/lib/golang/src/os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
	/usr/lib/golang/src/os/signal/signal.go:151 +0x2c

goroutine 35 [select, 2215 minutes]:
io.(*pipe).Read(0xc0004c0120, {0xc0003e8000, 0x1000, 0x7f38c67fba4f})
	/usr/lib/golang/src/io/pipe.go:57 +0xb7
io.(*PipeReader).Read(0x0, {0xc0003e8000, 0x100000000000000, 0x7f38f4e25638})
	/usr/lib/golang/src/io/pipe.go:134 +0x25
bufio.(*Scanner).Scan(0xc00005df28)
	/usr/lib/golang/src/bufio/scan.go:215 +0x865
github.com/sirupsen/logrus.(*Entry).writerScanner(0xc0003bead4, 0xc0004b2078, 0xc0004b4140)
	/root/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/writer.go:59 +0xa5
created by github.com/sirupsen/logrus.(*Entry).WriterLevel
	/root/go/pkg/mod/github.com/sirupsen/logrus@v1.8.1/writer.go:51 +0x3d6

goroutine 11 [semacquire]:
sync.runtime_SemacquireMutex(0x7f38a5a64658, 0x6f, 0xc000063e70)
	/usr/lib/golang/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc000756658)
	/usr/lib/golang/src/sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
	/usr/lib/golang/src/sync/mutex.go:81
github.com/yandex-cloud/geesefs/internal.(*Inode).TryFlush(0xc000756600)
	/root/geesefs/internal/file.go:1166 +0x12f
github.com/yandex-cloud/geesefs/internal.(*Goofys).Flusher(0xc00035a6c0)
	/root/geesefs/internal/goofys.go:551 +0x393
created by github.com/yandex-cloud/geesefs/internal.newGoofys
	/root/geesefs/internal/goofys.go:264 +0xa2f

goroutine 13 [runnable]:
syscall.Syscall(0x0, 0xb, 0xc033ed4000, 0x21000)
	/usr/lib/golang/src/syscall/asm_linux_amd64.s:20 +0x5
syscall.read(0xc0003dd8c0, {0xc033ed4000, 0x20300a, 0x41375d})
	/usr/lib/golang/src/syscall/zsyscall_linux_amd64.go:687 +0x4d
syscall.Read(...)
	/usr/lib/golang/src/syscall/syscall_unix.go:189
internal/poll.ignoringEINTRIO(...)
	/usr/lib/golang/src/internal/poll/fd_unix.go:582
internal/poll.(*FD).Read(0xc0003dd8c0, {0xc033ed4000, 0x21000, 0x21000})
	/usr/lib/golang/src/internal/poll/fd_unix.go:163 +0x285
os.(*File).read(...)
	/usr/lib/golang/src/os/file_posix.go:32
os.(*File).Read(0xc0004b2100, {0xc033ed4000, 0xc000477e08, 0x988bb9})
	/usr/lib/golang/src/os/file.go:119 +0x5e
github.com/jacobsa/fuse/internal/buffer.(*InMessage).Init(0xc02a177b80, {0x11b5d40, 0xc0004b2100})
	/root/go/pkg/mod/github.com/vitalif/fusego@v0.0.0-20220702223751-e304003d79bf/internal/buffer/in_message.go:59 +0x42
github.com/jacobsa/fuse.(*Connection).readMessage(0xc0000a7110)
	/root/go/pkg/mod/github.com/vitalif/fusego@v0.0.0-20220702223751-e304003d79bf/connection.go:342 +0x49
github.com/jacobsa/fuse.(*Connection).ReadOp(0xc0000a7110)
	/root/go/pkg/mod/github.com/vitalif/fusego@v0.0.0-20220702223751-e304003d79bf/connection.go:401 +0x48
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps(0xc00044f960, 0xc0000a7110)
	/root/go/pkg/mod/github.com/vitalif/fusego@v0.0.0-20220702223751-e304003d79bf/fuseutil/file_system.go:106 +0x7f
github.com/jacobsa/fuse.Mount.func1()
	/root/go/pkg/mod/github.com/vitalif/fusego@v0.0.0-20220702223751-e304003d79bf/mount.go:80 +0x38
created by github.com/jacobsa/fuse.Mount
	/root/go/pkg/mod/github.com/vitalif/fusego@v0.0.0-20220702223751-e304003d79bf/mount.go:79 +0x351

goroutine 14 [chan receive, 2215 minutes]:
main.registerSIGINTHandler.func1()
	/root/geesefs/main.go:53 +0x5e
created by main.registerSIGINTHandler
	/root/geesefs/main.go:51 +0x116

goroutine 149811 [IO wait]:
internal/poll.runtime_pollWait(0x7f38a6204e88, 0x72)
	/usr/lib/golang/src/runtime/netpoll.go:303 +0x85
internal/poll.(*pollDesc).wait(0xc00040a700, 0xc0002a9500, 0x0)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00040a700, {0xc0002a9500, 0x1465, 0x1465})
	/usr/lib/golang/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc00040a700, {0xc0002a9500, 0xc0002a9505, 0x279})
	/usr/lib/golang/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc026d54000, {0xc0002a9500, 0x6, 0xc00005f7f8})
	/usr/lib/golang/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc00000f4e8, {0xc0002a9500, 0x0, 0x4101ed})
	/usr/lib/golang/src/crypto/tls/conn.go:778 +0x3d
bytes.(*Buffer).ReadFrom(0xc0000aa278, {0x11b35a0, 0xc00000f4e8})
	/usr/lib/golang/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0000aa000, {0x11b5940, 0xc026d54000}, 0x2c0)
	/usr/lib/golang/src/crypto/tls/conn.go:800 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0000aa000, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:607 +0x112
crypto/tls.(*Conn).readRecord(...)
	/usr/lib/golang/src/crypto/tls/conn.go:575
crypto/tls.(*Conn).Read(0xc0000aa000, {0xc01c5ff000, 0x1000, 0x0})
	/usr/lib/golang/src/crypto/tls/conn.go:1278 +0x16f
net/http.(*persistConn).Read(0xc0000d0480, {0xc01c5ff000, 0xc0088ac7e0, 0xc00005fd30})
	/usr/lib/golang/src/net/http/transport.go:1926 +0x4e
bufio.(*Reader).fill(0xc025fa1b00)
	/usr/lib/golang/src/bufio/bufio.go:101 +0x103
bufio.(*Reader).Peek(0xc025fa1b00, 0x1)
	/usr/lib/golang/src/bufio/bufio.go:139 +0x5d
net/http.(*persistConn).readLoop(0xc0000d0480)
	/usr/lib/golang/src/net/http/transport.go:2087 +0x1ac
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1747 +0x1e05

goroutine 149781 [IO wait]:
internal/poll.runtime_pollWait(0x7f38a6205910, 0x72)
	/usr/lib/golang/src/runtime/netpoll.go:303 +0x85
internal/poll.(*pollDesc).wait(0xc0262be480, 0xc000b6e000, 0x0)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0262be480, {0xc000b6e000, 0x149e, 0x149e})
	/usr/lib/golang/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc0262be480, {0xc000b6e000, 0xc000b6e005, 0x10d})
	/usr/lib/golang/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc026d54010, {0xc000b6e000, 0xc026f3e120, 0xc0004747f8})
	/usr/lib/golang/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc001c3c588, {0xc000b6e000, 0x0, 0x4101ed})
	/usr/lib/golang/src/crypto/tls/conn.go:778 +0x3d
bytes.(*Buffer).ReadFrom(0xc0000aa978, {0x11b35a0, 0xc001c3c588})
	/usr/lib/golang/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0000aa700, {0x11b5940, 0xc026d54010}, 0x149e)
	/usr/lib/golang/src/crypto/tls/conn.go:800 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0000aa700, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:607 +0x112
crypto/tls.(*Conn).readRecord(...)
	/usr/lib/golang/src/crypto/tls/conn.go:575
crypto/tls.(*Conn).Read(0xc0000aa700, {0xc000b4b000, 0x1000, 0x0})
	/usr/lib/golang/src/crypto/tls/conn.go:1278 +0x16f
net/http.(*persistConn).Read(0xc00035ad80, {0xc000b4b000, 0x44ef20, 0xc000474ec8})
	/usr/lib/golang/src/net/http/transport.go:1926 +0x4e
bufio.(*Reader).fill(0xc03aeb8b40)
	/usr/lib/golang/src/bufio/bufio.go:101 +0x103
bufio.(*Reader).Peek(0xc03aeb8b40, 0x1)
	/usr/lib/golang/src/bufio/bufio.go:139 +0x5d
net/http.(*persistConn).readLoop(0xc00035ad80)
	/usr/lib/golang/src/net/http/transport.go:2087 +0x1ac
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1747 +0x1e05

goroutine 149782 [select]:
net/http.(*persistConn).writeLoop(0xc00035ad80)
	/usr/lib/golang/src/net/http/transport.go:2386 +0xfb
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1748 +0x1e65

goroutine 150294 [runnable]:
syscall.Syscall(0x14, 0xb, 0xc014c476e0, 0x2)
	/usr/lib/golang/src/syscall/asm_linux_amd64.s:20 +0x5
github.com/jacobsa/fuse.writev(0xc0000a7110, {0xc02931d3e0, 0x2, 0xdfdda0})
	/root/go/pkg/mod/github.com/vitalif/fusego@v0.0.0-20220702223751-e304003d79bf/writev.go:20 +0x97
github.com/jacobsa/fuse.(*Connection).Reply(0xc0000a7110, {0x11cd218, 0xc028a5f050}, {0x0, 0x0})
	/root/go/pkg/mod/github.com/vitalif/fusego@v0.0.0-20220702223751-e304003d79bf/connection.go:522 +0x625
github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0x1c, 0x113, {0x11cd218, 0xc028a5f050}, {0xdfdda0, 0xc02a177ac0})
	/root/go/pkg/mod/github.com/vitalif/fusego@v0.0.0-20220702223751-e304003d79bf/fuseutil/file_system.go:241 +0xac5
created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps
	/root/go/pkg/mod/github.com/vitalif/fusego@v0.0.0-20220702223751-e304003d79bf/fuseutil/file_system.go:123 +0x205

goroutine 149818 [IO wait]:
internal/poll.runtime_pollWait(0x7f38a6539598, 0x72)
	/usr/lib/golang/src/runtime/netpoll.go:303 +0x85
internal/poll.(*pollDesc).wait(0xc03ae9c380, 0xc0002aaa00, 0x0)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc03ae9c380, {0xc0002aaa00, 0x149e, 0x149e})
	/usr/lib/golang/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc03ae9c380, {0xc0002aaa00, 0xc0002aaa05, 0x10d})
	/usr/lib/golang/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc026d54130, {0xc0002aaa00, 0x60, 0xc0004787f8})
	/usr/lib/golang/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc00030dec0, {0xc0002aaa00, 0x0, 0x4101ed})
	/usr/lib/golang/src/crypto/tls/conn.go:778 +0x3d
bytes.(*Buffer).ReadFrom(0xc0000ab078, {0x11b35a0, 0xc00030dec0})
	/usr/lib/golang/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0000aae00, {0x11b5940, 0xc026d54130}, 0x149e)
	/usr/lib/golang/src/crypto/tls/conn.go:800 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0000aae00, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:607 +0x112
crypto/tls.(*Conn).readRecord(...)
	/usr/lib/golang/src/crypto/tls/conn.go:575
crypto/tls.(*Conn).Read(0xc0000aae00, {0xc00b60e000, 0x1000, 0x0})
	/usr/lib/golang/src/crypto/tls/conn.go:1278 +0x16f
net/http.(*persistConn).Read(0xc0000d0c60, {0xc00b60e000, 0x44ef20, 0xc000478ec8})
	/usr/lib/golang/src/net/http/transport.go:1926 +0x4e
bufio.(*Reader).fill(0xc045463b60)
	/usr/lib/golang/src/bufio/bufio.go:101 +0x103
bufio.(*Reader).Peek(0xc045463b60, 0x1)
	/usr/lib/golang/src/bufio/bufio.go:139 +0x5d
net/http.(*persistConn).readLoop(0xc0000d0c60)
	/usr/lib/golang/src/net/http/transport.go:2087 +0x1ac
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1747 +0x1e05

goroutine 149829 [IO wait]:
internal/poll.runtime_pollWait(0x7f38a5a8edb8, 0x72)
	/usr/lib/golang/src/runtime/netpoll.go:303 +0x85
internal/poll.(*pollDesc).wait(0xc00040ad00, 0xc000b81500, 0x0)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00040ad00, {0xc000b81500, 0x1465, 0x1465})
	/usr/lib/golang/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc00040ad00, {0xc000b81500, 0xc0004c0ba0, 0x3})
	/usr/lib/golang/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc026d54138, {0xc000b81500, 0x1, 0xc0004767f8})
	/usr/lib/golang/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc001c3c5b8, {0xc000b81500, 0x0, 0x4101ed})
	/usr/lib/golang/src/crypto/tls/conn.go:778 +0x3d
bytes.(*Buffer).ReadFrom(0xc0002ae278, {0x11b35a0, 0xc001c3c5b8})
	/usr/lib/golang/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0002ae000, {0x11b5940, 0xc026d54138}, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:800 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0002ae000, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:607 +0x112
crypto/tls.(*Conn).readRecord(...)
	/usr/lib/golang/src/crypto/tls/conn.go:575
crypto/tls.(*Conn).Read(0xc0002ae000, {0xc00e3c0000, 0x1000, 0x101000000d360f5})
	/usr/lib/golang/src/crypto/tls/conn.go:1278 +0x16f
net/http.(*persistConn).Read(0xc00035afc0, {0xc00e3c0000, 0x40b6bd, 0x60})
	/usr/lib/golang/src/net/http/transport.go:1926 +0x4e
bufio.(*Reader).fill(0xc012cb6300)
	/usr/lib/golang/src/bufio/bufio.go:101 +0x103
bufio.(*Reader).Peek(0xc012cb6300, 0x1)
	/usr/lib/golang/src/bufio/bufio.go:139 +0x5d
net/http.(*persistConn).readLoop(0xc00035afc0)
	/usr/lib/golang/src/net/http/transport.go:2087 +0x1ac
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1747 +0x1e05

goroutine 149830 [select]:
net/http.(*persistConn).writeLoop(0xc00035afc0)
	/usr/lib/golang/src/net/http/transport.go:2386 +0xfb
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1748 +0x1e65

goroutine 149756 [IO wait]:
internal/poll.runtime_pollWait(0x7f38cc7a3310, 0x72)
	/usr/lib/golang/src/runtime/netpoll.go:303 +0x85
internal/poll.(*pollDesc).wait(0xc00693c100, 0xc000b80000, 0x0)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/golang/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00693c100, {0xc000b80000, 0x149e, 0x149e})
	/usr/lib/golang/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc00693c100, {0xc000b80000, 0xc000b80005, 0x10d})
	/usr/lib/golang/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc026d54008, {0xc000b80000, 0x60, 0xc0002287f8})
	/usr/lib/golang/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc00030de90, {0xc000b80000, 0x0, 0x4101ed})
	/usr/lib/golang/src/crypto/tls/conn.go:778 +0x3d
bytes.(*Buffer).ReadFrom(0xc0000aa5f8, {0x11b35a0, 0xc00030de90})
	/usr/lib/golang/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0000aa380, {0x11b5940, 0xc026d54008}, 0x149e)
	/usr/lib/golang/src/crypto/tls/conn.go:800 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0000aa380, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:607 +0x112
crypto/tls.(*Conn).readRecord(...)
	/usr/lib/golang/src/crypto/tls/conn.go:575
crypto/tls.(*Conn).Read(0xc0000aa380, {0xc007b42000, 0x1000, 0x0})
	/usr/lib/golang/src/crypto/tls/conn.go:1278 +0x16f
net/http.(*persistConn).Read(0xc01db58000, {0xc007b42000, 0x44ef20, 0xc000228ec8})
	/usr/lib/golang/src/net/http/transport.go:1926 +0x4e
bufio.(*Reader).fill(0xc026bd5e60)
	/usr/lib/golang/src/bufio/bufio.go:101 +0x103
bufio.(*Reader).Peek(0xc026bd5e60, 0x1)
	/usr/lib/golang/src/bufio/bufio.go:139 +0x5d
net/http.(*persistConn).readLoop(0xc01db58000)
	/usr/lib/golang/src/net/http/transport.go:2087 +0x1ac
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1747 +0x1e05

goroutine 149819 [select]:
net/http.(*persistConn).writeLoop(0xc0000d0c60)
	/usr/lib/golang/src/net/http/transport.go:2386 +0xfb
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1748 +0x1e65

goroutine 149757 [select]:
net/http.(*persistConn).writeLoop(0xc01db58000)
	/usr/lib/golang/src/net/http/transport.go:2386 +0xfb
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1748 +0x1e65

goroutine 149812 [select]:
net/http.(*persistConn).writeLoop(0xc0000d0480)
	/usr/lib/golang/src/net/http/transport.go:2386 +0xfb
created by net/http.(*Transport).dialConn
	/usr/lib/golang/src/net/http/transport.go:1748 +0x1e65

**Comment by vitalif** [comment]
Привет, да, ошибка понятна, попробуйте сборку из master ветки - закоммитил исправление
