### ISSUE TITLE
geesefs started to panic with R2 recently

### ISSUE THREAD

**Issue by Felixoid** [yandex-cloud/geesefs#55]
Hello, yesterday I've started getting issues in syslog, and some programs stuck

```
Oct 27 06:40:29 ip-172-31-87-196 /usr/bin/geesefs[1444]: main.ERROR stacktrace from panic: deref inode 1896 (rpm/stable/repodata) by 4 from 2 #012goroutine 431264 [running]:#012runtime/debug.Stack(0xc0adce2bd8, 0xf7baa0, 0xc05aa5f4b0)#012#011/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/debug/stack.go:24 +0x9f#012github.com/yandex-cloud/geesefs/api/common.LogPanic(0xc0adce2f10)#012#011/home/runner/work/geesefs/geesefs/api/common/panic_logger.go:32 +0x76#012panic(0xf7baa0, 0xc05aa5f4b0)#012#011/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/panic.go:965 +0x1b9#012github.com/yandex-cloud/geesefs/internal.(*Inode).DeRef(0xc063d27680, 0x4, 0x768)#012#011/home/runner/work/geesefs/geesefs/internal/handles.go:361 +0x3a8#012github.com/yandex-cloud/geesefs/internal.(*Goofys).ForgetInode(0xc000408240, 0x133cad8, 0xc05aa63fb0, 0xc0597c1cb0, 0x0, 0x18)#012#011/home/runner/work/geesefs/geesefs/internal/goofys.go:1080 +0xd4#012github.com/yandex-cloud/geesefs/api/common.FusePanicLogger.ForgetInode(0x134cdc0, 0xc000408240, 0x133cad8, 0xc05aa63fb0, 0xc0597c1cb0, 0x0, 0x0)#012#011/home/runner/work/geesefs/geesefs/api/common/panic_logger.go:61 +0x89#012github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).handleOp(0xc0003b5260, 0xc0003589c0, 0x133cad8, 0xc05aa63fb0, 0xf4af20, 0xc05b8070e0)#012#011/home/runner/go/pkg/mod/github.com/vitalif/fusego@v0.0.0-20220702223751-e304003d79bf/fuseutil/file_system.go:160 +0xb58#012created by github.com/jacobsa/fuse/fuseutil.(*fileSystemServer).ServeOps#012#011/home/runner/go/pkg/mod/github.com/vitalif/fusego@v0.0.0-20220702223751-e304003d79bf/fuseutil/file_system.go:123 +0x1a5#012
Oct 27 06:40:29 ip-172-31-87-196 /usr/bin/geesefs[1444]: fuse.ERROR *fuseops.BatchForgetOp error: input/output error
```

The command how the bucket is mounted:

`/usr/bin/geesefs packages /home/ubuntu/r2 -o rw,user_id=1000,group_id=1000,--cheap,--file-mode=0666,--dir-mode=0777,--endpoint=https://****.r2.cloudflarestorage.com,--shared-config=/home/ubuntu/.r2_auth,--memory-limit=2050,--gc-interval=100,--max-flushers=2,--max-parallel-parts=3,--max-parallel-copy=2,dev,suid`

**Comment by vitalif** [comment]
This may indicate a bug somewhere around inode reference counting, or maybe it's even caused by flush errors due to cloudflare's HTTP 400 throttling. Did it reproduce after those 400?

**Comment by Felixoid** [comment]
It seems rather something unrelated. The issue happens during executing reprepro command adding new packages to Deb repo.

It's floating though. I can try reproduce it reliable

**Comment by vitalif** [comment]
Ok, if you manage to reproduce it then please do it with `--debug_fuse` enabled. It will generate a ton of logs, but it would help finding the issue

**Comment by Felixoid** [comment]
Is there a way to set a dedicated log output? I'd like to redirect it and not grep for geesefs in syslog

**Comment by vitalif** [comment]
`--log-file`

**Comment by Felixoid** [comment]
[geesefs-debug.log.xz.gz](https://github.com/yandex-cloud/geesefs/files/9888518/geesefs-debug.log.xz.gz) (GH accepts gz, but not xz. So, it's packed two times)

Here are the logs, I've been able to get the panic relatively quickly

**Comment by Felixoid** [comment]
generally, it looks like if I'm waiting until all flushes are done - I am more or less safe.

But I am not sure, how to do it properly. I'd be fine with slow, but reliable FS

**Comment by vitalif** [comment]
Good, seems I fixed both panics :)

"panic: runtime error: slice bounds out of range [:4096] with capacity 0" was caused by R2 flush errors (throttling is needed - #52...), now it will just return EIO instead of logging a panic

"panic: deref inode" was caused by not moving the reference count into the new inode entry when renaming a directory. So the kernel remembered 2 lookups for the directory but geesefs thought that it has only 1 (caused by mkdir). Also fixed it in master, you can check it out or wait until I make the release

**Comment by Felixoid** [comment]
Can I try the built binary from somewhere?

**Comment by vitalif** [comment]
Clone the repo and run `go build`

**Comment by Felixoid** [comment]
The latest binary looks better, although some race still has been there.

I've removed a directory, but it was still in place for some time, and the command to regenerate rpm repository failed. It's `/home/ubuntu/r2/rpm/stable/.repodata` in the log [geesefs-debug.log.xz.gz](https://github.com/yandex-cloud/geesefs/files/9912122/geesefs-debug.log.xz.gz)


- 15:53:45 I've removed it
- 15:53:56 it was accessed by createrepo, and still been there
- 15:54:10 I've listed it
- 15:55:10 I've removed it again

**Comment by vitalif** [comment]
Hm. GeeseFS remembers the removed state of the directory until all its contents are also removed from the server. And it seems from the log that it did everything correctly. But then at 15:53:56 the directory was rechecked from the server and `rpm/stable/.repodata/231ef358cbb1679f2911231ba1a0761dabcb6b27c882e5a84d122a6e0217cd3b-other.xml.gz` appeared which wasn't present before. The question is where did it come from? At 15:53:45 .repodata contained only 6 files:
```
2022/11/01 15:53:45.151739 fuse.DEBUG <-- ReadDir 60 rpm/stable/.repodata [c23e205778af5be4a278c2ca06b5dd5e6fae21ae-primary.xml.gz 3]
2022/11/01 15:53:45.151749 fuse.DEBUG <-- ReadDir 60 rpm/stable/.repodata [c276415499df4f24a89e3440bd391125f059073784903c6a666a652d0ea8f1ce-primary.xml.gz 4]
2022/11/01 15:53:45.151759 fuse.DEBUG <-- ReadDir 60 rpm/stable/.repodata [d73d8f117e22b9c3c03fcbfb8476f73eef6b9dab-primary.xml.gz 5]
2022/11/01 15:53:45.151768 fuse.DEBUG <-- ReadDir 60 rpm/stable/.repodata [e4723074e75aa4517be6a0e0ad7a4c55f77b8e069350739478516c90eeedf1c2-primary.sqlite.bz2 6]
2022/11/01 15:53:45.151777 fuse.DEBUG <-- ReadDir 60 rpm/stable/.repodata [repomd.xml 7]
2022/11/01 15:53:45.151808 fuse.DEBUG <-- ReadDir 60 rpm/stable/.repodata [repomd.xml.asc 8]
```
This `231ef358cbb1679f2911231ba1a0761dabcb6b27c882e5a84d122a6e0217cd3b-other.xml.gz` is what caused .repodata to reappear. Do you have any ideas?)

**Comment by Felixoid** [comment]
I think, it can be related to https://github.com/yandex-cloud/geesefs/issues/56 somehow

**Comment by vitalif** [comment]
Ok, then it seems this one is also caused by their buggy listings
