### ISSUE TITLE
Memory consumption is high compared to goofys

### ISSUE THREAD

**Issue by XSAM** [yandex-cloud/geesefs#70]
Hi, I am using geesefs to randomly read multiple objects on s3. But the memory consumption of geesefs is much higher than the goofys. When goofys uses 360MB memory, the geesefs uses 1.3GB memory even the ahead cache is disable.

geesefs options: `--no-implicit-dir,--memory-limit,1000,--read-ahead,0,--read-ahead-small,0,--read-ahead-large,0`

**Comment by vitalif** [comment]
Yeah, it's true :) by default GeeseFS uses 1 GB for in-memory data cache & buffers + additional memory for file metadata (~1 KB per 1 cached file) + program code, garbage collection, etc
The idea of original settings is that 100 MB readahead is optimal for linear read performance
You can try to reduce memory consumption by setting something like --memory-limit 250 --read-ahead-large 20480
But it will still consume memory for file metadata and so on
Regarding metadata, there's a plan to add a limit for it in the future too to be able to handle directories with, for example, 1 billion files in flat (without subdirectories) without OOM

**Comment by XSAM** [comment]
@vitalif Thanks for the reply.

With `--memory-limit 250 --read-ahead-large 20480` or even `--memory-limit 250 --read-ahead-large 0`, the memory usage is down to 600MB, but the performance of geesefs also drops 25%. I guess it is because of the GC.

**Comment by vitalif** [comment]
I think this is because of S3, goofys uses the same setting - load 5 20MB requests in parallel. If you reduce readahead even to 20MB from 100MB the performance slightly drops, probably because of the server architecture.

I'm closing the bug by now?
