### ISSUE TITLE
memory limit option not affect objects information cache, this result memory leak and OOM kill

### ISSUE THREAD

**Issue by kokh-an** [yandex-cloud/geesefs#82]
memory limit option not affect objects information cache, this result memory leak and OOM kill

as sample - cache limit - 1G, count of objects in s3 bucket - 10KK  (in tree structure)
on rapid random read this objects memory consumption fast grown and after small amount of time geesefs consume about 10G of RAM

i think need limit objects information cache, maybe as separated config option.

**Comment by vitalif** [comment]
Hi. Finally fixed in https://github.com/yandex-cloud/geesefs/releases/tag/v0.37.0 !
